source 'https://rubygems.org'

ruby '2.2.0'

gem 'rails', '4.2.0'
gem 'pg'

# Makes JSONApi-compliance stupid-easy.
# See https://github.com/cerebris/peeps for an example.
gem 'jsonapi-resources'

gem 'annotate', '~> 2.6.6'


group :development, :test do

  gem 'byebug'
  gem 'spring'
end

